### ISSUE TITLE
Permettre l'entrée des noms et lieux avec autocomplétion

### ISSUE THREAD

**Issue by a-gn** [a-gn/projetIHM1#25]
ComboBox éditables, avec une liste d'éléments filtrée (FilteredList ?) sur l'entrée de l'utilisateur. Pas d'ajout automatique d'élément.

Optionnel : proposer l'ouverture de la fenêtre d'ajout d'un utilisateur/lieu dans une option de la ComboBox quand l'entrée ne matche rien ou seulement quelques items.

**Comment by a-gn** [comment]
Méthode :
- rendre la ComboBox éditable
- wrapper ses items dans une FilteredList
- ajouter un listener sur la frappe, qui filtre la liste des items selon ce qu'on a écrit
- annuler le filtrage quand on sélectionne un élément, pour que les autres items soient de nouveau visibles (ça peut se faire en filtrant avec une chaîne vide)

**Comment by Gonogood** [comment]
S'assurer qu'un utilisateur non enregistré ne peut être entré

**Comment by a-gn** [comment]
Solution actuelle pas satisfaisante : pas de boutons de suppression dans les entrées de la ComboBox. Trouver un moyen de les ajouter ou utiliser la cell factory comme avant.

**Comment by a-gn** [comment]
Apparemment impossible de modifier la liste des items de la ComboBox pendant qu'on sélectionne un élément, y compris avec `Platform.runLater`.

**Comment by a-gn** [comment]
On manque de temps, on fera sans.
